#!/bin/sh
#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2019. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
#
# e2a: convert file on disk in EBCDIC to ASCII
#
syntax() {
	echo 'Syntax: e2a <file>: convert file from ebcdic to ascii' >&2
}
debug=0
verbose=0
while getopts ":vd" opt; do
	case ${opt} in
	d )
           	debug=1
		;;
	v )
           	verbose=1
		;;
	\?)
           	if [ "${OPTARG}" != "?" ]; then
                        echo "Invalid option: -$OPTARG" >&2
		fi
                syntax
		exit 4
		;;
	esac
done
shift $(expr $OPTIND - 1 )
if [ $# -ne 1 ]; then
	echo 'Need to specify a file to convert' >&2
	syntax
	exit 16
fi

if [ ! -f $1 ]; then
	echo 'File specified is not a regular file' >&2
	syntax
	exit 16
fi

iconv -f IBM-1047 -t ISO8859-1 <$1 >/tmp/ascii.$$

#msf - we should be fixing up the permissions here... 
mv /tmp/ascii.$$ $1
chtag -tc ISO8859-1 $1
