#!/bin/sh
export SMPE_CLASSPATH="/usr/lpp/smp/classes"
export SMPE_LABEL="SMPE Client Certificate"
export SMPE_RING="SMPERING"
export SMPE_SERVER="eccgw01.boulder.ibm.com"
export JAVA_HOME=/usr/lpp/java/J8.0_64
export SMPE_CSI="TST.GLOBAL.CSI"

export SMPE_FTPPORT=21
export SMPE_ORDER=...
export SMPE_FTPHOST=...
export SMPE_FTPSRCDIR=...
export SMPE_FTPUSER=...
export SMPE_FTPPW=...
export SMPE_FTPHASH=...
export SMPE_SIZE_MB=...

