#!/bin/sh
# Similar to the SMPPROC to make it easy to run SMP/E commands
# from 'sh'
#
#set -x

syntax() {
	echo "Syntax: smpe [-vdrlc]" >&2              
	echo "  -v: verbose output" >&2
	echo "  -d: debug output" >&2
	echo "  -c <csi file>: location of SMPCSI dataset" >&2
	echo "  -r <report file>: write SMPRPT output to <report file>" >&2
	echo "  -l <list file>: write SMPLIST output to <list file>" >&2
	echo "  -w <working directory>: set SMPWKDIR to <working directory>" >&2
	echo "SMPCNTL (SMP commands) specified via stdin" >&2
	echo "SMPOUT (SMP output) specified via stdout" >&2
	echo "Note:" >&2
	echo "  The CSI file can be specified with the environment variable SMPCSI instead of the -c option" >&2
	echo "  The work directory can be specified with the environment variable SMPWKDIR instead of the -w option" >&2
	echo "  The report file can be specified with the environment variable SMPRPT instead of the -r option" >&2
	echo "  The list file can be specified with the environment variable SMPLIST instead of the -l option" >&2
	exit 4
}

SMPLOG=DUMMY
SMPLOGA=DUMMY
SMPRPT=DUMMY
SMPSNAP=DUMMY
SMPDEBUG=DUMMY
SMPPUNCH=DUMMY
SYSPRINT=DUMMY
SMPOUT=stdout
SMPIN=stdin

if [ "${SMPCSI}" = "" ]; then
	SMPCSI=DUMMY
fi
if [ "${SMPLIST}" = "" ]; then
	SMPLIST=DUMMY
fi
if [ "${SMPRPT}" = "" ]; then
	SMPRPT=DUMMY
fi
if [ "${SMPWKDIR}" = "" ]; then
	SMPWKDIR=DUMMY
fi

debug=0
verbose=0

while getopts ":r:l:c:w:vd" opt; do
  case ${opt} in
    d )
      debug=1
      ;;
    v )
      verbose=1
      ;;
    c ) 
      SMPCSI=${OPTARG}
      ;;
    r ) 
      SMPRPT=${OPTARG}
      ;;
    l ) 
      SMPLIST=${OPTARG}
      ;;
    w ) 
      SMPWKDIR=${OPTARG}
      ;;
    \?) 	
      if [ ${OPTARG} != "?" ]; then
        msg zbrew ${InvalidOption} E "${OPTARG}"
      fi
      syntax
      exit 4
      ;;
  esac
done    	
shift $(expr $OPTIND - 1 )
if [ $# -gt 0 ]; then
        echo "No parameters other than options expected for smpe" >&2
 	syntax
        exit 16
fi  

mvscmdauth --pgm=gimsmp --smpcsi=${SMPCSI} --smpwkdir=${SMPWKDIR} --smplog=${SMPLOG} --smpout=${SMPOUT} --smprpt=${SMPRPT} --smpcntl=stdin --smplist=${SMPLIST} --smpout=stdout
