#!/bin/sh
# List non-VSAM datasets that start with a prefix.
# If '-l' is specified, the long list form, showing recfm, lrecl, blksize, dsorg, volumes is shown
# If you want to sort by time (for example), pipe it to sort, e.g. sort -b -k2 (TBD - add 't' option and perhaps others)
# Consider adding in an option to show how much is already written by dumping out the VTOC information - see vtocls
#
#set -x

ListBasic() {
	dlsraw $* | awk '/NONVSAM/ { print $2 }'
}

ListDetails() {
 pattern="('$1') HISTORY"
 tsocmd "listds ${pattern}" 2>/dev/null |
   awk 'BEGIN { inHeaderA=0; inHeaderB=0; ds=""; vol=""; recfm=""; lrecl=""; blksize=""; created=""; dsorg=""; }
       /--RECFM-LRECL-BLKSIZE-DSORG-CREATED---EXPIRES---SECURITY/ { inHeaderA=1; next; }
       /--VOLUMES--/ { inHeaderB=1; next; }
       /\ \ / { 
        if (inHeaderA) { 
          recfm=$1; lrecl=$2; blksize=$3; dsorg=$4; created=$5; inHeaderA=0; next; 
        } else if (inHeaderB) { 
          vol=$1; inHeaderB=0; 
          printf("%-45s ", ds);
          system("jdc " created);
          printf(" %2s %3s %5s %6s\n", dsorg, recfm, lrecl, vol); 
          next; 
        } 
      }
      { inHeaderA=0; inHeaderB=0; ds=$1; vol=""; recfm=""; lrecl=""; blksize=""; dsorg=""; created=""; next; }
     '
}
verbose() {
	if [[ ${verbose} -eq 1 ]]; then
		echo $*
	fi
}

set -o noglob
details=0
debug=0
verbose=0
while getopts ":lvd" opt; do
  case ${opt} in
    d )
      debug=1
      ;;
    l )
      details=1
      ;;
    v )
      verbose=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      syntax
      exit 4
      ;;
  esac
done
shift $(expr $OPTIND - 1 )
if [ $# -ne 1 ]; then
	echo 'Syntax: dls [-l] <dataset-prefix>'
	echo 'Example 1: dls IBMUSER.MVSCMD.* : list all datasets that start with IBMUSER.MVSCMD'
	exit 16
fi

if [ ${details} -eq 1 ]; then 
	files=`ListBasic "$*"`
	for f in $files; do
		ListDetails "$f"
	done
else
	ListBasic "$*"
fi
