#!/bin/sh
#
# display all catalog'ed datasets by printing out the master catalog
#
#set -x
debug=0
verbose=0
while getopts ":vd" opt; do
  case ${opt} in
    d )
      debug=1
      ;;
    v )
      verbose=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      syntax
      exit 4
      ;;
  esac
done
shift $(expr $OPTIND - 1 )
if [ $# -ne 0 ]; then
	echo 'Syntax: dlsall [options]'
	echo ' where [options] may be:'
	echo '  -d : debug'
	echo '  -v : verbose'
	exit 16
fi

loadmem=`opercmd 'display iplinfo' | awk ' /USED LOAD/ { print $4"("$2")" }'`
master=`cat "//'${loadmem}'" | awk ' /SYSCAT / { print substr($2,11) }'` 
catalogs=`pcatalog ${master} | awk '/CATALOG/ { print $2; }'`
if [[ ${debug} == 1 ]]; then
	echo "Master Catalog: ${master}"
fi
for catalog in ${catalogs}; do
	if [[ ${debug} == 1 ]]; then
		echo "Catalog: ${catalog}"
	fi
	pcatalog ${catalog} | awk '/ALIAS/ { next; } /CATALOG/ { next; } // { print $1 " " $2; }'
done
