#!/bin/sh
#
# list PDS members
#
#set -x
set -o noglob

if [ $# -ne 1 ]; then
	echo 'Syntax: mls <dataset>[(<member pattern>)]'
	echo 'Example: mls SYS1.PARMLIBi        <-- List all the members of SYS1.PARMLIB'
	echo 'Example: mls sys1.parmlib(iea*0?) <-- List all members of SYS1.PARMLIB that start with IEA and end with 0 followed by a single character'
	exit 16
else
	dataset=$(echo $1 | tr '[:lower:]' '[:upper:]')
	extension="${dataset##*(}"
	if [[ "${extension}" == "${dataset}" ]]; then
		pattern="*"
	else
		dataset="${dataset%(*}"
		pattern="${extension%)*}"
	fi
fi
members=`tsocmd listds "'"${dataset}"'" members 2>/dev/null | tail +7`
regexpattern=$(echo "${pattern}" | sed -e 's/\./\\./g' | sed -e 's/\*/\.\*/g' | sed -e 's/?/./g')
echo "${members}" | awk -vregexpattern="${regexpattern}" '// { if ($1 ~ "^"regexpattern) { print $1 } }'
