#!/bin/sh
#
# Move a dataset to a new volume
#
#set -x
if [[ $# -ne 2 ]]; then
	echo "Syntax: mvvol <dataset> <volume>"
	exit 16
fi
ds=$(echo ${1} | tr '[:lower:]' '[:upper:]')
srcvol=`echo " LISTCAT -\n ENTRIES(${ds}) VOLUME\n" | mvscmdauth --pgm=idcams --sysprint=* --sysin=stdin | awk '/VOLSER/ { print $1 }' | sed -e 's/VOLSER------------//'`
if [ -z ${srcvol} ]; then
	echo "Volume of dataset ${1} could not be determined"
	exit 16
fi

tgtvol=$2

echo " COPY DS ( -\n
       INC(${ds})) -\n
       LOGINDDNAME(DD1) -\n
       OUTDDNAME(DD2) -\n
       DELETE -\n
       ALLDATA(*) -\n
       ALLEXCP -\n
       SPHERE -\n
       TOL(ENQF) -\n
       CATALOG\n" | \
 mvscmdauth --pgm=adrdssu --sysin=stdin --sysprint=dummy --dd1=${srcvol},vol --dd2=${tgtvol},vol   
