#!/bin/sh
#
# pcatalog: print a catalog of all entries
#  If the -l option is specified, precede each entry with it's type
# 
#set -x
details=1
catalog=$1;

catalog=$(echo ${catalog} | tr '[:lower:]' '[:upper:]');
mvscmdauth --pgm=IDCAMS --sysprint=* --sysin=stdin <<zzz |
  LISTCAT CATALOG('${catalog}')
zzz
dsfilter
exit 0
