#!/bin/sh
#
# pcatalog: print a catalog of all entries
#  If the -l option is specified, precede each entry with it's type
# 
#set -x
debug=0
verbose=0
while getopts ":vd" opt; do
  case ${opt} in
    d )
      debug=1
      ;;
    v )
      verbose=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      syntax
      exit 4
      ;;
  esac
done
shift $(expr $OPTIND - 1 )
if [ $# -ne 1 ]; then
	echo 'Syntax: pcatalog <catalog>'
	exit 16
fi

catalog=$1;

catalog=$(echo ${catalog} | tr '[:lower:]' '[:upper:]');

if [[ ${debug} == 1 ]]; then
	echo "Print-Catalog: ${catalog}"
fi
mvscmdauth --pgm=IDCAMS --sysprint=* --sysin=stdin <<zzz |
  LISTCAT CATALOG('${catalog}')
zzz
dsfilter
exit 0
