#!/bin/sh
#
# pj: print active jobs
#
set -o noglob

function syntax {
  echo "pj: print active jobs"
  echo "Syntax: pj [<userid>|*]"
  echo " where <userid> defaults to the current user"
  echo " * prints all jobs for all users (you will likely need to specify '*' to avoid file expansion)"
}

function clean {
  str=$1
  str=`print ${str} | tr [:lower:] [:upper:]`
  print "${str##[=]}"
}
if test $# -eq 1; then
  userid=`clean ${1}`
  shift
else
  userid=`hlq`
fi
  
if test $# -gt 0; then
  echo "Unexpected parameters specified: $*"
  syntax
  exit 16
fi
opercmd "\$d jobq,QUEUE=XEQ,USERID=${userid}" 
