#!/bin/sh
#
# procwhence: find what dataset of the proclib concatenation that a member comes from
# e.g. procwhence IZUSVR1 will print out what dataset the member IZUSVR1 is in
#
#set -x
mem=`(echo $1 | tr '[:lower:]' '[:upper:]')`
ds=`pproc`
for d in $ds ; do
	mls "${d}" 2>/dev/null | grep -q "${mem}"
	if [ $? -eq 0 ]; then
		echo ${d}
		exit 0
	fi
done
exit 1
