#!/bin/sh
#
# permit a user to have access to a profile in a class
#
class=''
profile=''
id=${USER}
access='read'
while getopts ":p:c:i:a:" opt; do
  case ${opt} in
    p )
      profile=${OPTARG}
      ;;
    c )
      class=${OPTARG}
      ;;
    i )
      id=${OPTARG}
      ;;
    a )
      access=${OPTARG}
      ;;
  esac
done
if [[ ${class} = '' ]]; then
  echo "Need to specify a class to permit"
  exit 4 
fi
if [[ ${profile} = '' ]]; then
  echo "Need to specify a profile to permit"
  exit 4 
fi

tsocmd "PERMIT ${profile} CLASS(${class}) ID(${id}) ACCESS(${access})"
rc=$?
tsocmd "SETROPTS RACLIST(${class}) REFRESH"
exit ${rc}
