#!/bin/sh
#
# Script to return users and their access for a class/profile
# e.g. racfprofile facility IRR.DIGTCERT.ADD prints the list of users and their access for the class/profile
# Returns 0 if profile defined. Non-Zero otherwise
#
#set -x
export ME=$0
function syntax {
  echo "${ME} <class> <profile>"
}

class=$1
profile=$2
if [[ $# -ne 2 ]]; then
	syntax
	exit 16
fi
class=$(echo ${class} | tr '[:lower:]' '[:upper:]')
profile=$(echo ${profile} | tr '[:lower:]' '[:upper:]')

actual=`tsocmd "setr list" 2>/dev/null | trimlines 'ACTIVE CLASSES =' 'GENERIC PROFILE CLASSES ='`
actual=" ${actual} "
echo $actual | grep -q " ${class} "
if [ $? -gt 0 ]; then
	# class not defined
	exit 1  
fi
tsocmd "RLIST ${class} ${profile} ALL" 2>/dev/null | trimlines 'USER      ACCESS' '   ' | tail +2n | awk ' { print $1 " " $2 }'
exit 0
