#!/bin/sh
#
# List VSAM datasets that start with a prefix
# For details, add 'ALL' and switch to ENTRIES and specify one dataset...
#
if [ -z "$1" ]; then
	echo 'Syntax: vls <dataset-prefix>'
	echo 'Example: vls DBBG'
	exit 16
else
	datasetprefix=$1;
	datasetprefix=$(echo ${datasetprefix} | tr '[:lower:]' '[:upper:]')
fi
(
 echo " LISTCAT -\n LEVEL(${datasetprefix}\n" | 
   mvscmdauth --pgm=idcams --sysprint=* --sysin=stdin | awk '/0CLUSTER/ { print $3 }'
)
