#!/bin/sh
#
# vrm: remove a VSAM cluster
#
if [[ $# -ne 1 ]]; then
	echo "Syntax: vrm <vsam fully-qualified dataset>"
	exit 16
fi
vsam=$1
vsam=$(echo ${vsam} | tr '[:lower:]' '[:upper:]')
out=/tmp/$$.out
err=/tmp/$$.err
echo " DELETE ${vsam}\n" | mvscmdauth --pgm="IDCAMS" --args="MARGINS(2 72)" --sysin=stdin --sysprint=* >${out} 2>${err}
rc=$?
if [[ ${rc} -gt 0 ]]; then
  cat ${out} >&2
  cat ${err} >&2
else 
  rm -f ${out}
  rm -f ${err}
fi

exit ${rc}
