export ZOS_USER="tstradm"
export ZOS_HOST="fultonm.zosaas.ibm.com"
export ZOS_GIT_USER="Mike Fulton"
export ZOS_GIT_EMAIL="fultonm@ca.ibm.com"
export ROCKET_TOOLS_DIR="/Users/fultonm/Documents/Development/RocketTools"
export ZOS_TOOLS_ROOT="/zaas1/tools"
